### ISSUE TITLE
IOException in ClarifaiRequester

### ISSUE THREAD

**Issue by peterlitvak** [Clarifai/clarifai-java#11]
We get the this exception while trying to tag some of the MP4 video files:
```
Jul 01 04:05:07 ip-10-130-102-211 PRODUCTION:  com.clarifai.api.exception.ClarifaiException: IOException
Jul 01 04:05:07 ip-10-130-102-211 PRODUCTION:   at com.clarifai.api.ClarifaiRequester.executeOnce(ClarifaiRequester.java:100)
Jul 01 04:05:07 ip-10-130-102-211 PRODUCTION:   at com.clarifai.api.ClarifaiRequester.execute(ClarifaiRequester.java:39)
Jul 01 04:05:07 ip-10-130-102-211 PRODUCTION:   at com.clarifai.api.ClarifaiClient.recognize(ClarifaiClient.java:88)
```
any suggestions?

**Comment by kevinmost** [comment]
Hi! We've just pushed an update to this client to v2 that uses our new v2 APIs available [here](https://developer-preview.clarifai.com/docs/). The v1 clients have officially been deprecated.

Our v2 API does not yet support video.

**Comment by peterlitvak** [comment]
doesn't seem like the API reference page (for java) is up yet
```
Tag or commit '2.0.0' not found. Rechecking.
```

**Comment by kevinmost** [comment]
Hey @peterlitvak, thanks for checking back! It should be available now: https://jitpack.io/com/github/clarifai/clarifai-java/2.0.0/javadoc/

Sorry about that! When you checked, I don't think our release candidate had fully propagated through yet.

I also recommend reading our quick-start guide [here](https://developer-preview.clarifai.com/docs/). Please let me know if you have any questions or feedback. :)

**Comment by peterlitvak** [comment]
Thank you!
