### ISSUE TITLE
No way to shutdown client?

### ISSUE THREAD

**Issue by artem-snopkov** [Clarifai/clarifai-java#25]
Hi! 
Is there any way to close ClarifaiClient in order to close underlying http connections?

**Comment by kevinmost** [comment]
Hi @artem-snopkov,

Thanks for the feature request. I have added a `.close()` method to the latest version (2.1.0) of the API client. You can grab that now off Maven Central, jCenter, or JitPack.

Note that you probably won't have to close the client manually, however. We use OkHttp, which is designed to reclaim unused resources that go idle, and no network requests are made if you aren't invoking any methods on the client, so you can let it sit around without being closed and it shouldn't leak any memory or make any requests.

**Comment by artem-snopkov** [comment]
Thank you 👍
