### ISSUE TITLE
Cannot get customized language for prediction API

### ISSUE THREAD

**Issue by felixqk** [Clarifai/clarifai-java#29]
Hi, Clarifai Team,

I am testing the Clarifai API for integration with our business. One issue I encountered and not be able to find a good reference is the customized language. I saw general 1.3 supported other languages but not be able to reproduce it in Java API:

final ClarifaiClient client = new ClarifaiBuilder("key", "sec").buildSync();

final List<ClarifaiOutput<Concept>> predictionResults =
    client.getDefaultModels().generalModel().predict().withInputs(
        ClarifaiInput.forImage(ClarifaiImage.of("https://samples.clarifai.com/metro-north.jpg"))
) .executeSync().get();

In the API doc I didn't find how to specify language and my application settings are already set default language other than English, still, only English tag returned.

 Could you help to take a look?

Best,

Felix

**Comment by kevinmost** [comment]
Hi @felixqk, we don't have support for languages other than English yet in the v2 API. Once that support is added, we can add it to the API clients. 

Our [v1 API](https://github.com/Clarifai/clarifai-java/tree/1.2.0) doesn't have a lot of the functionality of v2, but supports different languages.

**Comment by kevinmost** [comment]
I'm going to close this issue since we're blocked until other languages are supported in the v2 API. As this is an officially-supported API client, the feature will be added as soon as the API supports it.
