### ISSUE TITLE
Empty payload for additional video inputs when bulk processing

### ISSUE THREAD

**Issue by derekprovance** [Clarifai/clarifai-java#60]
If multiple videos are queued using `input -> ClarifaiInput.forVideo(input.getUrl()));`

`client.getDefaultModels().generalVideoModel()
            .predict()
            .withInputs(inputs)
            .executeSync().get();`

The first video receives tags relevant to the video but all videos after receive an empty data ArrayList on the ClarifaiOutput object.

Temporary fix will be queuing our videos one by one

**Comment by rok-povsic** [comment]
Hi @derekprovance ,

currently, server-side only supports predicting one video at a time. We might allow prediction of multiple videos / batching in the same request in the future. Batching images predictions is possible.

For now, please run predicts for one video at the time.

Thank you,
Rok
