### ISSUE TITLE
Problem using the library with Android

### ISSUE THREAD

**Issue by hanuor** [Clarifai/clarifai-java#61]
Hi,
I'm trying to use this library with Android by doing this inside my Gradle file:
`implementation 'com.clarifai.clarifai-api2:core:2.4.0'`
Problem is that it throwing me a RuntimeException saying - Unable to merge dex.

Any fix for this?

**Comment by rok-povsic** [comment]
@hanuor Hi, could you try the solutions posted [on this StackOverflow page](https://stackoverflow.com/questions/46267621/unable-to-merge-dex)? Thank you.
