### ISSUE TITLE
IOException from running sample

### ISSUE THREAD

**Issue by jetonbacaj** [Clarifai/clarifai-java#8]
Hi folks,

I am attempting to run the example, but I keep getting an IOException being thrown when the folling line in ClarifaiRequester.java is evaluated;

`boolean isSuccess = (conn.getResponseCode() >= 200 && conn.getResponseCode() < 300);`

I modified the Main.java class to instantiate the ClarifaiClient with my appId and secret.

Please let me know if you need further information.

Thanks!

**Comment by keithito** [comment]
Hi, can you send along the stack trace?

**Comment by jetonbacaj** [comment]
Hi @keithito,

This is what I get;

`Exception in thread "main" com.clarifai.api.exception.ClarifaiException: IOException
	at com.clarifai.api.ClarifaiRequester.executeOnce(ClarifaiRequester.java:100)
	at com.clarifai.api.ClarifaiRequester.execute(ClarifaiRequester.java:39)
	at com.clarifai.api.ClarifaiClient.recognize(ClarifaiClient.java:88)
	at com.clarifai.samples.clirecognizer.Main.main(Main.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.io.IOException: Error writing to server
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:665)
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:677)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1533)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.clarifai.api.ClarifaiRequester.executeOnce(ClarifaiRequester.java:75)
	... 8 more`

Let me know if you need further information.

Thanks.

**Comment by keithito** [comment]
Thanks, @jetonbacaj! What version of the JVM are you using? Can you send the output of running "java -version". Also, how large is the image or video that you're trying to recognize?

**Comment by jetonbacaj** [comment]
I am using Java 8; 
`$ java -version`
`java version "1.8.0_60"`
`Java(TM) SE Runtime Environment (build 1.8.0_60-b27)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)`


The image is about 3-4MB.  I tried feeding the same image on the web demo, and it worked there, if that matters.

Thanks!

**Comment by keithito** [comment]
I noticed you're running from within IntelliJ. Can you try running at the command-line and seeing if your request succeeds? Also, does your request succeed if you send URLs instead of image bytes?

Generally, you'd expect to see "java.io.IOException: Error writing to server" from HttpURLConnection if your connection to the server was closed while you were uploading image data. But that would be pretty unusual if you're only uploading a few MB.

**Comment by jetonbacaj** [comment]
Hi @keithito,

Sorry to disappearing - I was sucked into something else till now.

I am indeed running this from IntelliJ.  Attempting to do this via CLI is proving to be not as straight forward as I had hoped.
I went into `/Users/jeton/Desktop/code/clarifai-java/samples/command-line/src/main/java/com/clarifai/samples/clirecognizer`

and compiled the class like so;

`javac -cp "/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar:/Users/jeton/Desktop/code/clarifai-java/samples/command-line/target/classes:/Users/jeton/.m2/repository/com/clarifai/clarifai-api-java/1.2.0/clarifai-api-java-1.2.0.jar:/Users/jeton/.m2/repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar" Main.java
`

However, when I attempt to run the resulting Main.class, like so 

`java Main` 
or 
`java -cp . Main`, 
or even 
`java -cp "/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar:/Users/jeton/Desktop/code/clarifai-java/samples/command-line/target/classes:/Users/jeton/.m2/repository/com/clarifai/clarifai-api-java/1.2.0/clarifai-api-java-1.2.0.jar:/Users/jeton/.m2/repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar" Main
` 

and they all yield the following error;

`Error: Could not find or load main class Main`

I'd appreciate some help on this front, as I am sure I am missing something big (aside from lack of caffeine :smile: )


I tried running the example with a URL (in IntelliJ) instead of image bytes, and that seems to work fine.

Thanks a ton!

**Comment by kevinmost** [comment]
Hi! We've just pushed an update to this client to v2 that uses our new v2 APIs available [here](https://developer-preview.clarifai.com/docs/). The v1 clients have officially been deprecated.

Our Quick Start -> Predict guide has a quick way to get up and running with general-model tags for images, which is analogous to getting tags back for an image from the v1 API client. You could try our new client and see if it solves your issues. If it doesn't, please feel free to open a new issue. :)
